import { useEffect, useState } from 'react';
import { Icon } from '../../components/Icon';
import { Dialog, EmptyState, Notice } from '../../components/Primitives';
import { api } from '../../lib/api';
import type { Playlist } from '../../types';

export function Playlists() {
  const [items, setItems] = useState<Playlist[]>([]); const [createOpen, setCreateOpen] = useState(false); const [selected, setSelected] = useState<Set<string>>(new Set()); const [status, setStatus] = useState<string | null>(null);
  const load = () => void api.playlists().then((response) => setItems(response.items)).catch((error) => setStatus(error instanceof Error ? error.message : 'No se pudieron cargar las playlists'));
  useEffect(load, []);
  const create = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const playlist = await api.createPlaylist(String(data.get('name')), String(data.get('rule'))); setItems((current) => [...current, playlist]); setCreateOpen(false); };
  const exportSelected = async (format: 'm3u8' | 'apple-xml') => { try { const result = await api.exportPlaylists([...selected], format); setStatus(`${result.files.length} archivo(s) guardado(s) en _Playlists.`); } catch (error) { setStatus(error instanceof Error ? error.message : 'No se pudo exportar'); } };
  return <div className="page-stack"><header className="page-header"><div><p className="eyebrow">Colecciones vivas</p><h1>Playlists</h1><p>Reglas persistentes sobre pistas finales verificadas.</p></div><button className="button primary" onClick={() => setCreateOpen(true)}>Nueva playlist</button></header>{status && <Notice tone={status.includes('guardado') ? 'success' : 'error'}>{status}</Notice>}
    {items.length === 0 ? <EmptyState icon="playlists" title="Aún no hay playlists">Crea una colección de favoritas verificadas. Las reglas por artista, género y década permanecen bloqueadas hasta su validación.<div className="empty-action"><button className="button primary" onClick={() => setCreateOpen(true)}>Crear la primera</button></div></EmptyState> : <><div className="playlist-grid">{items.map((playlist) => <label className="playlist-card" key={playlist.id}><input type="checkbox" checked={selected.has(playlist.id)} onChange={() => setSelected((current) => { const next = new Set(current); if (next.has(playlist.id)) next.delete(playlist.id); else next.add(playlist.id); return next; })}/><div className="playlist-art"><Icon name="playlists" size={28}/></div><div><strong>{playlist.name}</strong><span>{playlist.rule}</span><small>{playlist.tracks} canciones</small></div></label>)}</div><div className="export-bar"><div><strong>Exportar selección</strong><span>M3U8 portátil o XML para Música de Apple</span></div><button className="button secondary" disabled={!selected.size} onClick={() => void exportSelected('m3u8')}><Icon name="download"/>M3U8</button><button className="button secondary" disabled={!selected.size} onClick={() => void exportSelected('apple-xml')}><Icon name="download"/>Apple XML</button></div></>}
    <Dialog open={createOpen} title="Nueva playlist automática" eyebrow="Regla local" onClose={() => setCreateOpen(false)} actions={<><button className="button ghost" onClick={() => setCreateOpen(false)}>Cancelar</button><button form="playlist-form" className="button primary" type="submit">Crear playlist</button></>}><form id="playlist-form" className="form-grid" onSubmit={(event) => void create(event)}><label><span>Nombre</span><input required name="name" placeholder="Favoritas Rock"/></label><label><span>Regla certificada</span><select name="rule"><option value="favorites">Favoritas con copia final verificada</option></select></label></form></Dialog>
  </div>;
}
