import { useEffect, useState } from 'react';
import { Notice } from '../../components/Primitives';
import { api } from '../../lib/api';
import type { AppSettings } from '../../types';

const DEFAULTS: AppSettings = { mode: 'simulation', updateTags: false, artwork: false, preserveArtwork: true, preferLossless: true, provider: { musicbrainzEnabled: false, openaiEnabled: false, webSearchEnabled: false, openaiConfigured: false, model: null, maxRequests: 100, maxWebRequests: 10 } };

function Toggle({ label, description, checked, disabled, onChange }: { label: string; description: string; checked: boolean; disabled?: boolean; onChange: (checked: boolean) => void }) {
  return <label className={`toggle-row ${disabled ? 'disabled' : ''}`}><span><strong>{label}</strong><small>{description}</small></span><input type="checkbox" checked={checked} disabled={disabled} onChange={(event) => onChange(event.target.checked)}/><i aria-hidden="true"/></label>;
}

export function ProviderSettings({ onSettingsChanged }: { onSettingsChanged: (settings: AppSettings) => void }) {
  const [settings, setSettings] = useState<AppSettings>(DEFAULTS); const [loading, setLoading] = useState(true); const [status, setStatus] = useState<string | null>(null); const [apiKey, setApiKey] = useState('');
  useEffect(() => { void api.settings().then(setSettings).catch(() => setStatus('No se pudo leer la configuración del servicio. Se muestran valores seguros por defecto.')).finally(() => setLoading(false)); }, []);
  const patchProvider = (changes: Partial<AppSettings['provider']>) => setSettings((current) => ({ ...current, provider: { ...current.provider, ...changes } }));
  const save = async () => { setLoading(true); setStatus(null); try { const saved = await api.saveSettings(settings); setSettings(saved); onSettingsChanged(saved); setStatus('Configuración guardada.'); } catch (error) { setStatus(error instanceof Error ? error.message : 'No se pudo guardar'); } finally { setLoading(false); } };
  const saveKey = async () => { setLoading(true); setStatus(null); try { const result = await api.saveOpenAIKey(apiKey.trim()); const updated = { ...settings, provider: { ...settings.provider, openaiConfigured: result.configured, openaiEnabled: result.configured } }; if (result.configured) await api.saveSettings(updated); setSettings(updated); onSettingsChanged(updated); setApiKey(''); setStatus(result.configured ? 'Clave de OpenAI guardada en memoria y activada.' : 'Clave de OpenAI eliminada.'); } catch (error) { setStatus(error instanceof Error ? error.message : 'No se pudo guardar la clave'); } finally { setLoading(false); } };
  return <div className="page-stack settings-page"><header className="page-header"><div><p className="eyebrow">Control y privacidad</p><h1>Configuración</h1><p>Las integraciones de red están separadas y desactivadas inicialmente.</p></div><button className="button primary" onClick={() => void save()} disabled={loading}>Guardar cambios</button></header>{status && <Notice tone={status.startsWith('Configuración') || status.startsWith('Clave') ? 'success' : 'error'}>{status}</Notice>}
    <section className="settings-section"><header><span>01</span><div><h2>Modo de organización</h2><p>Simulación es el punto de partida y nunca escribe.</p></div></header><div className="mode-grid">{(['simulation', 'safe'] as const).map((mode) => <label key={mode} className={settings.mode === mode ? 'selected' : ''}><input type="radio" name="mode" checked={settings.mode === mode} onChange={() => setSettings({ ...settings, mode })}/><strong>{mode === 'simulation' ? 'Simulación' : mode === 'safe' ? 'Seguro' : 'Organizar'}</strong><span>{mode === 'simulation' ? 'Vista previa, cero escrituras' : mode === 'safe' ? 'Copia verificada, conserva origen' : 'Copia; retirar origen es otra acción'}</span></label>)}</div></section>
    <section className="settings-section"><header><span>02</span><div><h2>OpenAI</h2><p>Coloca tu API key aquí. No se muestra de nuevo ni se guarda en la base de datos.</p></div></header><div className="settings-card"><div className="api-key-row"><label><span>Clave API de OpenAI</span><input type="password" autoComplete="off" spellCheck={false} value={apiKey} onChange={(event) => setApiKey(event.target.value)} placeholder={settings.provider.openaiConfigured ? 'Clave configurada · pega otra para reemplazarla' : 'sk-…'}/></label><button className="button secondary" type="button" disabled={loading || !apiKey.trim()} onClick={() => void saveKey()}>Guardar API key</button></div><Toggle label="Usar OpenAI como fallback" description={settings.provider.openaiConfigured ? `API configurada · ${settings.provider.model ?? 'modelo del servidor'}` : 'Guarda una API key para habilitarlo.'} checked={settings.provider.openaiEnabled} disabled={!settings.provider.openaiConfigured} onChange={(value) => patchProvider({ openaiEnabled: value })}/><Toggle label="MusicBrainz" description="Opcional; requiere MUSICBRAINZ_CONTACT en el servicio." checked={settings.provider.musicbrainzEnabled} onChange={(value) => patchProvider({ musicbrainzEnabled: value })}/><p className="privacy-copy">Solo se envían nombres saneados y tags relevantes; nunca audio ni rutas completas. Cada candidato requiere aceptación humana.</p></div></section>
    <section className="settings-section"><header><span>03</span><div><h2>Archivos y calidad</h2><p>El organizador operativo es copy-only y conserva siempre los originales.</p></div></header><div className="settings-card"><Notice tone="neutral">La escritura de tags y descarga de portadas permanecen bloqueadas hasta completar la certificación por contenedor. El helper aislado no se invoca durante la organización.</Notice><Toggle label="Preferir calidad lossless" description="Solo recomienda un representante; nunca elimina otra versión." checked={settings.preferLossless} onChange={(value) => setSettings({ ...settings, preferLossless: value })}/></div></section>
  </div>;
}
