import { useEffect, useState } from 'react';
import { Icon } from '../../components/Icon';
import { Notice } from '../../components/Primitives';
import { api } from '../../lib/api';
import type { AppSettings, RootGrant, ScanJob, Stats } from '../../types';

const DEFAULTS: AppSettings = { mode: 'simulation', updateTags: false, artwork: false, preserveArtwork: true, preferLossless: true, language: 'es', theme: 'light', provider: { musicbrainzEnabled: false, openaiEnabled: false, webSearchEnabled: false, openaiConfigured: false, model: null, maxRequests: 100, maxWebRequests: 10 } };
const THEMES: Array<{ id: AppSettings['theme']; name: string; desc: string }> = [
  { id: 'light', name: 'Kawaii claro', desc: 'Pastel rosado, celeste y arcoíris.' },
  { id: 'tokyo', name: 'Tokyo Night', desc: 'Oscuro azul/morado elegante.' },
  { id: 'github-dark', name: 'GitHub Dark', desc: 'Contraste sobrio para trabajo largo.' },
  { id: 'dracula', name: 'Dracula', desc: 'Oscuro morado con acentos vivos.' },
];
const copy = {
  es: { title: 'Configuración', privacy: 'Control y privacidad', subtitle: 'Define carpetas, modo de trabajo, idioma, tema, integraciones y limpieza.', folders: 'Carpetas de trabajo', source: 'Origen musical', destination: 'Destino organizado', chooseSource: 'Elegir origen', chooseDestination: 'Elegir destino', scan: 'Analizar origen', none: 'No seleccionado', behavior: 'Comportamiento', language: 'Idioma', theme: 'Tema', light: 'Claro', dark: 'Oscuro', mode: 'Modo de organización', simulation: 'Simulación', safe: 'Seguro', integrations: 'OpenAI y MusicBrainz', apiKey: 'Clave API de OpenAI', saveKey: 'Guardar API key', openai: 'Usar OpenAI como fallback', maintenance: 'Mantenimiento', reset: 'Resetear app limpia', resetHelp: 'Elimina base interna, roots autorizadas, historial, planes, cache, errores y clave OpenAI en memoria. No toca archivos de música.', save: 'Guardar cambios' },
  en: { title: 'Settings', privacy: 'Control and privacy', subtitle: 'Set folders, workflow mode, language, theme, integrations, and cleanup.', folders: 'Working folders', source: 'Music source', destination: 'Organized destination', chooseSource: 'Choose source', chooseDestination: 'Choose destination', scan: 'Scan source', none: 'Not selected', behavior: 'Behavior', language: 'Language', theme: 'Theme', light: 'Light', dark: 'Dark', mode: 'Organization mode', simulation: 'Simulation', safe: 'Safe', integrations: 'OpenAI and MusicBrainz', apiKey: 'OpenAI API key', saveKey: 'Save API key', openai: 'Use OpenAI as fallback', maintenance: 'Maintenance', reset: 'Reset clean app', resetHelp: 'Deletes internal database state, authorized roots, history, plans, cache, errors, and in-memory OpenAI key. It never touches music files.', save: 'Save changes' },
};

function Toggle({ label, description, checked, disabled, onChange }: { label: string; description: string; checked: boolean; disabled?: boolean; onChange: (checked: boolean) => void }) {
  return <label className={`toggle-row ${disabled ? 'disabled' : ''}`}><span><strong>{label}</strong><small>{description}</small></span><input type="checkbox" checked={checked} disabled={disabled} onChange={(event) => onChange(event.target.checked)}/><i aria-hidden="true"/></label>;
}

export function ProviderSettings({ roots, onRootsChanged, onScanChanged, onSettingsChanged, onReset }: { roots: RootGrant[]; onRootsChanged: () => Promise<void>; onScanChanged: (job: ScanJob) => void; onSettingsChanged: (settings: AppSettings) => void; onReset: (stats?: Stats) => void }) {
  const [settings, setSettings] = useState<AppSettings>(DEFAULTS); const [loading, setLoading] = useState(true); const [status, setStatus] = useState<{ tone: 'success' | 'error' | 'warning'; text: string } | null>(null); const [apiKey, setApiKey] = useState('');
  const source = roots.find((root) => root.role === 'source'); const destination = roots.find((root) => root.role === 'destination'); const t = copy[settings.language];
  useEffect(() => { void api.settings().then((value) => { setSettings(value); document.documentElement.dataset.theme = value.theme; document.documentElement.lang = value.language; }).catch(() => setStatus({ tone: 'error', text: 'No se pudo leer la configuración.' })).finally(() => setLoading(false)); }, []);
  const update = (next: AppSettings) => { setSettings(next); document.documentElement.dataset.theme = next.theme; document.documentElement.lang = next.language; onSettingsChanged(next); };
  const patchProvider = (changes: Partial<AppSettings['provider']>) => update({ ...settings, provider: { ...settings.provider, ...changes } });
  const save = async (next = settings) => { setLoading(true); setStatus(null); try { const saved = await api.saveSettings(next); update(saved); setStatus({ tone: 'success', text: next.language === 'en' ? 'Settings saved.' : 'Configuración guardada.' }); } catch (error) { setStatus({ tone: 'error', text: error instanceof Error ? error.message : 'No se pudo guardar' }); } finally { setLoading(false); } };
  const chooseRoot = async (role: RootGrant['role']) => { setLoading(true); setStatus(null); try { await api.authorizeRoot(role); await onRootsChanged(); setStatus({ tone: 'success', text: role === 'source' ? 'Origen autorizado.' : 'Destino autorizado.' }); } catch (error) { setStatus({ tone: 'error', text: error instanceof Error ? error.message : 'No se pudo autorizar la carpeta' }); } finally { setLoading(false); } };
  const scanSource = async () => { if (!source) return; setLoading(true); try { onScanChanged(await api.scan(source.id)); setStatus({ tone: 'success', text: 'Origen analizado.' }); } catch (error) { setStatus({ tone: 'error', text: error instanceof Error ? error.message : 'No se pudo analizar' }); } finally { setLoading(false); } };
  const saveKey = async () => { setLoading(true); setStatus(null); try { const result = await api.saveOpenAIKey(apiKey.trim()); const updated = { ...settings, provider: { ...settings.provider, openaiConfigured: result.configured, openaiEnabled: result.configured } }; if (result.configured) await api.saveSettings(updated); update(updated); setApiKey(''); setStatus({ tone: 'success', text: result.configured ? 'API key guardada en memoria.' : 'API key eliminada.' }); } catch (error) { setStatus({ tone: 'error', text: error instanceof Error ? error.message : 'No se pudo guardar la clave' }); } finally { setLoading(false); } };
  const resetAll = async () => { setLoading(true); setStatus(null); try { await api.resetAll(); await onRootsChanged(); onReset(); setStatus({ tone: 'success', text: settings.language === 'en' ? 'Clean reset complete.' : 'Reset limpio completado.' }); } catch (error) { setStatus({ tone: 'error', text: error instanceof Error ? error.message : 'No se pudo resetear' }); } finally { setLoading(false); } };

  return <div className="page-stack settings-page"><header className="page-header"><div><p className="eyebrow">{t.privacy}</p><h1>{t.title}</h1><p>{t.subtitle}</p></div><button className="button primary" onClick={() => void save()} disabled={loading}>{t.save}</button></header>{status && <Notice tone={status.tone}>{status.text}</Notice>}
    <section className="settings-section"><header><span>01</span><div><h2>{t.folders}</h2><p>Define primero el origen y el destino. Organización no debe pedirlos a mitad del flujo.</p></div></header><div className="settings-card folder-card"><div className="folder-row"><strong>{t.source}</strong><code>{source?.path ?? t.none}</code><button className="button secondary" onClick={() => void chooseRoot('source')} disabled={loading}><Icon name="folder"/>{t.chooseSource}</button><button className="button primary" onClick={() => void scanSource()} disabled={loading || !source}><Icon name="play"/>{t.scan}</button></div><div className="folder-row"><strong>{t.destination}</strong><code>{destination?.path ?? t.none}</code><button className="button secondary" onClick={() => void chooseRoot('destination')} disabled={loading}><Icon name="folder"/>{t.chooseDestination}</button></div></div></section>
    <section className="settings-section"><header><span>02</span><div><h2>{t.behavior}</h2><p>Idioma y tema se aplican al instante; el modo se guarda en el servicio local.</p></div></header><div className="settings-card settings-grid-card"><label><span>{t.language}</span><select value={settings.language} onChange={(event) => { const next = { ...settings, language: event.target.value as AppSettings['language'] }; update(next); void save(next); }}><option value="es">Español</option><option value="en">English</option></select></label><label><span>{t.theme}</span><select value={settings.theme} onChange={(event) => { const next = { ...settings, theme: event.target.value as AppSettings['theme'] }; update(next); void save(next); }}>{THEMES.map((theme) => <option key={theme.id} value={theme.id}>{theme.name}</option>)}</select></label><label><span>{t.mode}</span><select value={settings.mode} onChange={(event) => { const next = { ...settings, mode: event.target.value as AppSettings['mode'] }; update(next); void save(next); }}><option value="simulation">{t.simulation}</option><option value="safe">{t.safe}</option></select></label></div></section>
    <section className="settings-section"><header><span>03</span><div><h2>Personalización</h2><p>Elige una apariencia. Mantiene adornos kawaii si quieres, pero los temas oscuros son sobrios y útiles.</p></div></header><div className="theme-grid">{THEMES.map((theme) => <button key={theme.id} className={`theme-card theme-${theme.id} ${settings.theme === theme.id ? 'active' : ''}`} onClick={() => { const next = { ...settings, theme: theme.id }; update(next); void save(next); }}><i/><strong>{theme.name}</strong><span>{theme.desc}</span></button>)}</div></section>
    <section className="settings-section"><header><span>04</span><div><h2>{t.integrations}</h2><p>La clave no se muestra otra vez ni se guarda en la base de datos.</p></div></header><div className="settings-card"><div className="api-key-row"><label><span>{t.apiKey}</span><input type="password" autoComplete="off" spellCheck={false} value={apiKey} onChange={(event) => setApiKey(event.target.value)} placeholder={settings.provider.openaiConfigured ? 'Configurada · pega otra para reemplazar' : 'sk-…'}/></label><button className="button secondary" type="button" disabled={loading || !apiKey.trim()} onClick={() => void saveKey()}>{t.saveKey}</button></div><Toggle label={t.openai} description={settings.provider.openaiConfigured ? 'API configurada.' : 'Guarda una API key para habilitarlo.'} checked={settings.provider.openaiEnabled} disabled={!settings.provider.openaiConfigured} onChange={(value) => patchProvider({ openaiEnabled: value })}/><Toggle label="MusicBrainz" description="Opcional; requiere MUSICBRAINZ_CONTACT en el servicio." checked={settings.provider.musicbrainzEnabled} onChange={(value) => patchProvider({ musicbrainzEnabled: value })}/><p className="privacy-copy">Nunca se envía audio ni rutas completas.</p></div></section>
    <section className="settings-section"><header><span>05</span><div><h2>{t.maintenance}</h2><p>{t.resetHelp}</p></div></header><div className="settings-card maintenance-card"><button className="button danger" onClick={() => void resetAll()} disabled={loading}>{t.reset}</button></div></section>
  </div>;
}
