import { useEffect, useMemo, useState } from 'react';
import { Icon } from '../../components/Icon';
import { Dialog, EmptyState, Notice } from '../../components/Primitives';
import { api } from '../../lib/api';
import { formatBytes } from '../../lib/library';
import type { Mode, Plan, PlanBuildJob, RootGrant } from '../../types';

type WorkOption = 'copy' | 'metadata' | 'duplicates' | 'playlists' | 'tags';
const OPTIONS: Array<{ id: WorkOption; label: string; description: string; disabled?: boolean }> = [
  { id: 'copy', label: 'Copiar y renombrar', description: 'Crea la biblioteca organizada en el destino.' },
  { id: 'metadata', label: 'Leer metadatos', description: 'Usa artista, álbum, título y calidad detectados.' },
  { id: 'duplicates', label: 'Detectar duplicados', description: 'Agrupa por hash y evita trabajos redundantes.' },
  { id: 'playlists', label: 'Preparar playlists', description: 'Se desbloquea tras una ejecución verificada.' },
  { id: 'tags', label: 'Escribir tags', description: 'Bloqueado hasta certificación por formato.', disabled: true },
];

function PercentCard({ label, done, total }: { label: string; done: number; total: number }) {
  const percent = total > 0 ? Math.min(100, Math.round((done / total) * 100)) : 0;
  return <article className="progress-card compact-progress"><div className="progress-head"><div><p className="eyebrow">{label}</p><h2>{total ? `${done.toLocaleString('es-ES')} / ${total.toLocaleString('es-ES')}` : 'Pendiente'}</h2></div><strong>{percent}%</strong></div><div className={`progress-track ${total ? '' : 'indeterminate'}`}><i style={total ? { width: `${percent}%` } : undefined}/></div></article>;
}

export function PlanPreview({ plan, roots, mode, onPlanChanged }: { plan: Plan | null; roots: RootGrant[]; mode: Mode; onPlanChanged: (plan: Plan) => void }) {
  const [dialog, setDialog] = useState<'approve' | 'apply' | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [buildJob, setBuildJob] = useState<PlanBuildJob | null>(null);
  const [options, setOptions] = useState<Record<WorkOption, boolean>>({ copy: true, metadata: true, duplicates: true, playlists: false, tags: false });
  const source = roots.find((root) => root.role === 'source'); const destination = roots.find((root) => root.role === 'destination');
  const approvalBlockReason = plan?.conflicts ? `${plan.conflicts} conflictos bloquean la aprobación. Abre los elementos marcados, corrige metadatos/nombres o elige un destino vacío.` : plan?.state === 'stale' ? 'La revisión está desactualizada. Ejecuta una nueva revisión.' : null;
  const applyDone = useMemo(() => plan?.items.filter((item) => item.state === 'committed').length ?? 0, [plan]);
  useEffect(() => {
    if (!plan || !['applying', 'cancel_requested'].includes(plan.state)) return;
    const timer = window.setInterval(() => void api.plan().then((next) => next && onPlanChanged(next)).catch(() => undefined), 1200);
    return () => window.clearInterval(timer);
  }, [plan, onPlanChanged]);
  useEffect(() => {
    if (!buildJob || buildJob.id === 'starting' || !['queued', 'running'].includes(buildJob.state)) return;
    const timer = window.setInterval(() => void api.planBuild(buildJob.id).then((next) => { setBuildJob(next); if (next.state === 'completed' && next.plan) { onPlanChanged(next.plan); setBusy(false); } if (next.state === 'failed' || next.state === 'cancelled') setBusy(false); }).catch(() => setBusy(false)), 700);
    return () => window.clearInterval(timer);
  }, [buildJob, onPlanChanged]);
  const authorize = async (role: RootGrant['role']) => { setBusy(true); setError(null); try { await api.authorizeRoot(role); window.location.reload(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo autorizar la carpeta'); } finally { setBusy(false); } };
  const execute = async () => { if (!source || !destination) { setError('Primero elige origen y destino.'); return; } setBusy(true); setError(null); setBuildJob({ id: 'starting', state: 'queued', phase: 'Iniciando revisión', processed: 0, total: 0 }); try { const started = await api.startPlanBuild(destination.id, mode); setBuildJob({ id: started.jobId, state: 'queued', phase: 'Preparando revisión', processed: 0, total: 0 }); } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo iniciar la revisión'); setBuildJob(null); setBusy(false); } };
  const cancelBuild = async () => { if (!buildJob || buildJob.id === 'starting') return; setBusy(true); try { await api.cancelPlanBuild(buildJob.id); setBuildJob({ ...buildJob, state: 'cancelled', phase: 'Revisión cancelada' }); } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo cancelar la revisión'); } finally { setBusy(false); } };
  const approve = async () => { if (!plan) return; setBusy(true); try { onPlanChanged(await api.approvePlan(plan.id, plan.revision, mode)); setDialog(null); } catch (reason) { setError(reason instanceof Error ? reason.message : 'El plan no pudo aprobarse'); } finally { setBusy(false); } };
  const apply = async () => { if (!plan) return; setBusy(true); try { await api.applyPlan(plan.id, plan.revision); setDialog(null); onPlanChanged({ ...plan, state: 'applying' }); } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo aplicar el plan'); } finally { setBusy(false); } };
  const stop = async () => { if (!plan) return; setBusy(true); try { await api.cancelPlan(plan.id); onPlanChanged({ ...plan, state: 'cancel_requested' }); } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo detener'); } finally { setBusy(false); } };

  return <div className="page-stack"><header className="page-header"><div><p className="eyebrow">Centro de ejecución</p><h1>Ejecutar RESONANCE</h1><p>El flujo completo está aquí: elegir carpetas, revisar opciones, ejecutar revisión, aprobar y aplicar.</p></div>{plan && <span className="revision">Revisión {plan.revision}</span>}</header>
    <section className="execution-map"><article><span>1</span><strong>Carpetas</strong><p>Origen: {source?.path ?? 'pendiente'} · Destino: {destination?.path ?? 'pendiente'}</p><div className="button-row"><button className="button secondary" onClick={() => void authorize('source')} disabled={busy}><Icon name="folder"/>Origen</button><button className="button secondary" onClick={() => void authorize('destination')} disabled={busy}><Icon name="folder"/>Destino</button></div></article><article><span>2</span><strong>Qué procesar</strong><p>Selecciona los cambios que RESONANCE debe preparar.</p></article><article><span>3</span><strong>Revisión</strong><p>Calcula rutas, conflictos, tamaño y metadatos. No escribe.</p></article><article><span>4</span><strong>Aplicación</strong><p>Copia, verifica y muestra progreso. STOP corta antes del siguiente archivo.</p></article></section>
    <section className="options-grid">{OPTIONS.map((option) => <label key={option.id} className={option.disabled ? 'disabled' : ''}><input type="checkbox" checked={options[option.id]} disabled={option.disabled} onChange={(event) => setOptions((current) => ({ ...current, [option.id]: event.target.checked }))}/><span><strong>{option.label}</strong><small>{option.description}</small></span></label>)}</section>
    <section className="plan-controls"><div><span className="control-index">RUN</span><div><strong>Ejecutar revisión funcional</strong><p>Lee origen/destino, calcula nombres finales, conflictos y conteos. Todavía no escribe archivos.</p></div></div><button className="button primary" onClick={() => void execute()} disabled={!source || !destination || busy || !options.copy}>{busy ? 'PROCESANDO…' : 'EJECUTAR REVISIÓN'}</button></section>
    {buildJob && <section className="work-monitor" role="status" aria-live="polite"><div className="progress-head"><div><p className="eyebrow">Proceso de revisión</p><h2>{buildJob.phase}</h2></div><strong>{buildJob.total > 0 ? `${Math.round((buildJob.processed / buildJob.total) * 100)}%` : '0%'}</strong></div><div className={`progress-track ${buildJob.total ? '' : 'indeterminate'}`}><i style={buildJob.total ? { width: `${Math.round((buildJob.processed / buildJob.total) * 100)}%` } : undefined}/></div><div className="progress-meta"><span>{buildJob.processed.toLocaleString('es-ES')} procesados</span><span>{buildJob.total.toLocaleString('es-ES')} totales</span><span>{buildJob.conflicts ?? 0} bloqueos</span><span>{buildJob.warnings ?? 0} advertencias</span></div>{buildJob.current && <div className="current-file"><b>Ahora:</b><code>{buildJob.current}</code></div>}{buildJob.error && <Notice tone="error">{buildJob.error}</Notice>}<div className="button-row"><button className="button danger" onClick={() => void cancelBuild()} disabled={buildJob.id === 'starting' || !['queued','running'].includes(buildJob.state)}>Cancelar revisión</button></div></section>}
    {error && <Notice tone="error">{error}</Notice>}
    {!source || !destination ? <Notice tone="warning">Falta elegir {source ? 'destino' : destination ? 'origen' : 'origen y destino'}. Usa los botones de arriba; no necesitas buscar otra pantalla.</Notice> : null}
    {!plan ? <EmptyState icon="duplicates" title="Aún no hay revisión">Cuando ejecutes la revisión verás conteos, conflictos y el botón para aprobar/aplicar.</EmptyState> : <>
      <div className="plan-summary"><article><span>Incluidos</span><strong>{plan.items.filter((item) => item.selected).length}</strong></article><article><span>Advertencias</span><strong>{plan.warnings ?? 0}</strong></article><article><span>Bloqueos</span><strong className={plan.conflicts ? 'danger-text' : ''}>{plan.conflicts}</strong></article><article><span>Espacio estimado</span><strong>{formatBytes(plan.estimatedBytes)}</strong></article></div>
      <PercentCard label={plan.state === 'applying' || plan.state === 'cancel_requested' ? 'Ejecución' : 'Revisión preparada'} done={plan.state === 'applying' || plan.state === 'cancel_requested' ? applyDone : plan.items.length} total={plan.items.length}/>
      {plan.audit && <Notice tone="success">Auditoría: {plan.audit.audioFiles?.toLocaleString('es-ES') ?? plan.items.length.toLocaleString('es-ES')} archivos de audio, {formatBytes(plan.audit.audioBytes ?? plan.estimatedBytes)} de audio, {plan.audit.nonAudioFiles?.toLocaleString('es-ES') ?? 0} archivos no-audio ignorados.</Notice>}
      {plan.space && <Notice tone={plan.space.sufficientForCopy ? 'success' : 'warning'}>{plan.space.sufficientForCopy ? `Espacio OK para copiar: requiere ${formatBytes(plan.space.requiredBytes)} y hay ${formatBytes(plan.space.availableBytes)} disponibles.` : plan.space.sameVolume ? `Espacio insuficiente para duplicar: requiere ${formatBytes(plan.space.requiredBytes)} y hay ${formatBytes(plan.space.availableBytes)}. Como origen y destino están en el mismo disco, la alternativa segura es un modo avanzado de MOVER: renombrar/mover con verificación y liberar el espacio del origen después de confirmar cada archivo.` : `Espacio insuficiente para copiar: requiere ${formatBytes(plan.space.requiredBytes)} y hay ${formatBytes(plan.space.availableBytes)}. Libera espacio o usa un destino en el mismo disco para poder mover con verificación.`}</Notice>}
      {approvalBlockReason && <Notice tone="warning">No puedes aprobar todavía: {approvalBlockReason}</Notice>}
      {plan.conflicts > 0 && <Notice tone="warning">“Destino bloqueado” significa que se sobrescribiría un archivo diferente o dos canciones terminan con el mismo nombre. Corrige metadatos o elige otro destino.</Notice>}
      <section className="plan-list" aria-label="Cambios propuestos">{plan.items.slice(0, 120).map((item) => <article className={item.conflict ? 'has-conflict' : item.warning ? 'has-warning' : item.state === 'committed' ? 'has-success' : ''} key={item.id}><div className="path-flow"><span><b>ORIGINAL</b><code>{item.originalPath}</code></span><i aria-hidden="true">↓</i><span><b>DESTINO</b><code>{item.destinationPath}</code></span></div>{item.state && <div className="conflict warning"><Icon name="check"/>Estado: {item.state}</div>}{item.conflict && <div className="conflict"><Icon name="warning"/>{item.conflict}</div>}{item.warning && <div className="conflict warning"><Icon name="check"/>{item.warning}</div>}</article>)}</section>
      <footer className="sticky-actions"><div><strong>{approvalBlockReason ?? (plan.state === 'approved' ? 'Revisión aprobada: pulsa APLICAR Y EJECUTAR' : plan.state === 'applying' ? 'Ejecutando cambios verificados' : 'Aprobar no ejecuta cambios')}</strong><p>{approvalBlockReason ? 'El botón está desactivado hasta resolver esa causa.' : 'El botón principal para hacer el trabajo está aquí abajo.'}</p></div>{plan.state === 'applying' || plan.state === 'cancel_requested' ? <button className="button danger" onClick={() => void stop()} disabled={busy || plan.state === 'cancel_requested'}><Icon name="stop"/>STOP</button> : plan.state === 'approved' ? <button className="button primary" disabled={plan.conflicts > 0} onClick={() => setDialog('apply')}>APLICAR Y EJECUTAR</button> : <button className="button primary" disabled={Boolean(approvalBlockReason)} title={approvalBlockReason ?? undefined} onClick={() => setDialog('approve')}>REVISAR Y APROBAR</button>}</footer>
    </>}
    <Dialog open={dialog === 'approve'} title="Aprobar esta revisión" eyebrow="Confirmación 1 de 2" onClose={() => setDialog(null)} actions={<><button className="button ghost" onClick={() => setDialog(null)}>Volver</button><button className="button primary" onClick={() => void approve()} disabled={busy}>Solo aprobar</button></>}><p>Esto congela la lista. Todavía NO copia archivos.</p></Dialog>
    <Dialog open={dialog === 'apply'} danger title="Aplicar y ejecutar" eyebrow="Confirmación final" onClose={() => setDialog(null)} actions={<><button className="button ghost" onClick={() => setDialog(null)}>Cancelar</button><button className="button danger" onClick={() => void apply()} disabled={busy || mode === 'simulation'}>Sí, aplicar y ejecutar</button></>}><Notice tone="warning">Escribe solo en el destino autorizado. No borra originales ni sobrescribe archivos diferentes.</Notice><p>Se ejecutará la revisión {plan?.revision}. Verás porcentaje y puedes usar STOP.</p></Dialog>
  </div>;
}
