import { useState } from 'react';
import { Icon } from '../../components/Icon';
import { Dialog, EmptyState, Notice } from '../../components/Primitives';
import { api } from '../../lib/api';
import { formatBytes } from '../../lib/library';
import type { Mode, Plan, RootGrant } from '../../types';

export function PlanPreview({ plan, roots, mode, onPlanChanged }: { plan: Plan | null; roots: RootGrant[]; mode: Mode; onPlanChanged: (plan: Plan) => void }) {
  const [dialog, setDialog] = useState<'approve' | 'apply' | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const destination = roots.find((root) => root.role === 'destination');
  const authorizeDestination = async () => { setBusy(true); setError(null); try { await api.authorizeRoot('destination'); window.location.reload(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo autorizar el destino'); } finally { setBusy(false); } };
  const execute = async () => { if (!destination) return; setBusy(true); setError(null); try { onPlanChanged(await api.createPlan(destination.id, mode)); } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo crear el plan'); } finally { setBusy(false); } };
  const approve = async () => { if (!plan) return; setBusy(true); try { onPlanChanged(await api.approvePlan(plan.id, plan.revision, mode)); setDialog(null); } catch (reason) { setError(reason instanceof Error ? reason.message : 'El plan no pudo aprobarse'); } finally { setBusy(false); } };
  const apply = async () => { if (!plan) return; setBusy(true); try { await api.applyPlan(plan.id, plan.revision); setDialog(null); onPlanChanged({ ...plan, state: 'applying' }); } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo aplicar el plan'); } finally { setBusy(false); } };
  const stop = async () => { if (!plan) return; setBusy(true); try { await api.cancelPlan(plan.id); onPlanChanged({ ...plan, state: 'cancel_requested' }); } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo detener'); } finally { setBusy(false); } };

  return <div className="page-stack"><header className="page-header"><div><p className="eyebrow">Ejecución guiada</p><h1>Organización</h1><p>Primero se genera un plan de solo lectura; después se aprueba; al final se aplica.</p></div>{plan && <span className="revision">Revisión {plan.revision}</span>}</header>
    <section className="plan-controls"><div><span className="control-index">01</span><div><strong>Destino nativo</strong><p>{destination ? destination.path : 'Aún no autorizado'}</p></div></div><button className="button secondary" onClick={() => void authorizeDestination()} disabled={busy}><Icon name="folder"/>{destination ? 'Cambiar destino' : 'Autorizar destino'}</button></section>
    <section className="plan-controls"><div><span className="control-index">02</span><div><strong>Ejecutar revisión</strong><p>Lee origen/destino, calcula nombres finales y NO escribe archivos todavía.</p></div></div><button className="button primary" onClick={() => void execute()} disabled={!destination || busy}>{busy ? 'Procesando…' : 'EJECUTAR REVISIÓN'}</button></section>
    {error && <Notice tone="error">{error}</Notice>}
    {!plan ? <EmptyState icon="duplicates" title="No hay una revisión todavía">Autoriza un destino y ejecuta la revisión para comparar ORIGINAL → DESTINO.</EmptyState> : <>
      <div className="plan-summary"><article><span>Incluidos</span><strong>{plan.items.filter((item) => item.selected).length}</strong></article><article><span>Advertencias</span><strong>{plan.warnings ?? 0}</strong></article><article><span>Bloqueos</span><strong className={plan.conflicts ? 'danger-text' : ''}>{plan.conflicts}</strong></article><article><span>Espacio estimado</span><strong>{formatBytes(plan.estimatedBytes)}</strong></article></div>
      {plan.audit && <Notice tone="success">Auditoría: {plan.audit.audioFiles?.toLocaleString('es-ES') ?? plan.items.length.toLocaleString('es-ES')} archivos de audio, {formatBytes(plan.audit.audioBytes ?? plan.estimatedBytes)} de audio, {plan.audit.nonAudioFiles?.toLocaleString('es-ES') ?? 0} archivos no-audio ignorados.</Notice>}
      {plan.conflicts > 0 && <Notice tone="warning">“Destino bloqueado” significa que se sobrescribiría un archivo diferente o dos canciones terminan con el mismo nombre. Recomendación: corregir metadatos o elegir otro destino. Si el destino contiene el mismo archivo por tamaño/hash, ahora queda como advertencia aprobable.</Notice>}
      {plan.state === 'applying' && <Notice tone="warning">Aplicando cambios. Usa STOP si detectas un error; se detendrá antes del siguiente archivo.</Notice>}
      {plan.state === 'cancel_requested' && <Notice tone="warning">STOP solicitado. La app terminará la operación actual y no iniciará más archivos.</Notice>}
      <section className="plan-list" aria-label="Cambios propuestos">{plan.items.length === 0 ? <EmptyState title="El plan no contiene cambios">No hay pistas elegibles con la configuración actual.</EmptyState> : plan.items.map((item) => <article className={item.conflict ? 'has-conflict' : item.warning ? 'has-warning' : ''} key={item.id}><div className="path-flow"><span><b>ORIGINAL</b><code>{item.originalPath}</code></span><i aria-hidden="true">↓</i><span><b>DESTINO</b><code>{item.destinationPath}</code></span></div>{item.conflict && <div className="conflict"><Icon name="warning"/>{item.conflict}</div>}{item.warning && <div className="conflict warning"><Icon name="check"/>{item.warning}</div>}</article>)}</section>
      <footer className="sticky-actions"><div><strong>{plan.state === 'approved' ? 'Revisión aprobada: falta aplicar' : plan.state === 'applying' ? 'Aplicando' : 'Aprobar no ejecuta cambios'}</strong><p>Los originales se conservan; el modo seguro copia y verifica byte a byte.</p></div>{plan.state === 'applying' || plan.state === 'cancel_requested' ? <button className="button danger" onClick={() => void stop()} disabled={busy || plan.state === 'cancel_requested'}><Icon name="stop"/>STOP</button> : plan.state === 'approved' ? <button className="button primary" disabled={plan.conflicts > 0} onClick={() => setDialog('apply')}>APLICAR Y EJECUTAR</button> : <button className="button primary" disabled={plan.conflicts > 0 || plan.state === 'stale'} onClick={() => setDialog('approve')}>REVISAR Y APROBAR</button>}</footer>
    </>}
    <Dialog open={dialog === 'approve'} title="Aprobar esta revisión" eyebrow="Confirmación 1 de 2" onClose={() => setDialog(null)} actions={<><button className="button ghost" onClick={() => setDialog(null)}>Volver</button><button className="button primary" onClick={() => void approve()} disabled={busy}>Solo aprobar</button></>}><p>Se congelarán {plan?.items.filter((item) => item.selected).length ?? 0} acciones exactamente como aparecen. Esto todavía NO copia ni renombra archivos.</p><div className="mode-callout"><strong>Siguiente paso</strong><span>Después verás el botón APLICAR Y EJECUTAR. Si prefieres, puedes dejar la revisión aprobada y aplicarla más tarde.</span></div></Dialog>
    <Dialog open={dialog === 'apply'} danger title="Aplicar y ejecutar" eyebrow="Confirmación final" onClose={() => setDialog(null)} actions={<><button className="button ghost" onClick={() => setDialog(null)}>Cancelar</button><button className="button danger" onClick={() => void apply()} disabled={busy || mode === 'simulation'}>Sí, aplicar y ejecutar</button></>}><Notice tone="warning">Esta acción escribe solo en el destino autorizado. No borra originales ni sobrescribe archivos diferentes.</Notice><p>Se ejecutará únicamente la revisión {plan?.revision}. Puedes usar STOP durante la ejecución.</p></Dialog>
  </div>;
}
